# Generated by Django 3.1.3 on 2021-12-17 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kural', '0002_auto_20211209_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='KuralMarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kural_id', models.IntegerField()),
                ('tirukkural', models.TextField(null=True)),
                ('munnurai', models.TextField(null=True)),
                ('judge_kural_marks', models.FloatField(default=0.0)),
                ('judge_porul_marks', models.FloatField(default=0.0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judge', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
