# Generated by Django 3.1.3 on 2022-10-08 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kural', '0006_competitiondate_registration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AssignStudent',
        ),
    ]
